# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataQuery2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(null=True)),
                ('item_google', models.TextField(null=True)),
                ('item_bing', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='results_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('query_id', models.IntegerField()),
                ('answer', models.TextField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('now_query_id', models.IntegerField()),
            ],
        ),
    ]
